### ISSUE TITLE
Maven central

### ISSUE THREAD

**Issue by vbauer** [eveliotc/carbonite#1]
Could you please deploy this library on Maven Central or some other repository?

**Comment by casidiablo** [comment]
Yes @eveliotc don't be lazy. You might as well move to Gradle!

**Comment by eveliotc** [comment]
@vbauer Thanks for requesting this, will resolve within this week

@casidiablo Gradle originally was being used see fa4166c1890f44c87d4763499163524547620119

**Comment by eveliotc** [comment]
@vbauer 

You can now use snapshots as follows

``` groovy
  repositories {
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
  }

  dependencies {
     compile 'info.evelio:carbonite:0.1-SNAPSHOT'
  }
```

**Comment by vbauer** [comment]
Thank you very much!
